# Generated by Django 3.2 on 2021-05-17 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_category'),
        ('accounts', '0002_alter_useraccount_avatar'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='client_of_store',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_lines_of_order',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product_type',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_cost',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='username',
        ),
        migrations.AddField(
            model_name='order',
            name='active',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='accounts.useraccount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NP', 'Not Paid'), ('PD', 'Paid'), ('SH', 'Shipped'), ('DL', 'Delivered')], default='NP', max_length=2),
        ),
        migrations.AddField(
            model_name='order',
            name='sum',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderline',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order_lines', to='orders.order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderline',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderline',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='products.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='date_of_submission',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='number_of_products',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='orderline',
            unique_together={('product', 'order')},
        ),
        migrations.RemoveField(
            model_name='orderline',
            name='product_in_order_lines',
        ),
        migrations.RemoveField(
            model_name='orderline',
            name='product_price',
        ),
    ]
