# Generated by Django 3.2 on 2021-05-18 20:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210517_1025'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-id',)},
        ),
        migrations.RemoveField(
            model_name='order',
            name='sum',
        ),
        migrations.AddField(
            model_name='order',
            name='invoice_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='orderline',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='date_of_submission',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterUniqueTogether(
            name='orderline',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='orderline',
            name='number_of_products',
        ),
    ]
