# Generated by Django 3.2 on 2021-05-04 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=256)),
                ('category', models.CharField(choices=[('DARK', 'Dark Chocolate'), ('MILKY', 'Milky Chocolate'), ('CANDY', 'Candy')], default='DARK', max_length=5)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
