# Generated by Django 3.2 on 2021-05-08 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210504_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(default=None, upload_to='images/'),
            preserve_default=False,
        ),
    ]
