# Generated by Django 3.2 on 2021-05-08 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='products_under_category',
            new_name='category',
        ),
    ]
