# Generated by Django 3.2 on 2021-05-18 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('SUBS', 'Subscription to a service'), ('ITEM', 'Item shipped to the customer')], default='SUBS', max_length=4),
        ),
    ]
